Repository markusressel/fan2go, pull requests merged in 2025-06, with the labels that each got.

#377 Feature/#375 abstraction for fan mode
  cmd/fan/mode.go
  internal/controller/controller.go
  internal/controller/controller_test.go
  internal/fans/cmd.go
  internal/fans/cmd_test.go
  internal/fans/common.go
  internal/fans/file.go
  internal/fans/file_test.go
  internal/fans/hwmon.go
  internal/fans/hwmon_test.go
Labels: enhancement

#373 Support nvidia GPUs using go-nvml
  README.md
  cmd/detect.go
  cmd/sensor/sensor.go
  fan2go.yaml
  go.mod
  go.sum
  internal/backend.go
  internal/configuration/fancontroller.go
  internal/configuration/fans.go
  internal/configuration/sensors.go
  internal/configuration/validation.go
  internal/configuration/validation_test.go
  internal/controller/controller.go
  internal/fans/common.go
  internal/fans/nvidia.go
  internal/nvidia/nvidia.go
  internal/nvidia_base/nvidia_base.go
  internal/sensors/common.go
  internal/sensors/nvidia.go
  main.go
Labels: enhancement

#383 print Control "Mode" instead of only "Auto"
  README.md
  cmd/detect.go
  internal/controller/controller_test.go
  internal/fans/cmd.go
  internal/fans/cmd_test.go
  internal/fans/common.go
  internal/fans/file.go
  internal/fans/file_test.go
  internal/fans/hwmon.go
  internal/fans/hwmon_test.go
  internal/fans/nvidia.go
Labels: enhancement

#394 Feature/#388 pid curve docs
  README.md
Labels: documentation

#398 Crash if RPM data is nil
  internal/controller/controller.go
Labels: bug

#396 Allow compiling without go-nvml support
  .github/workflows/go.yml
  Makefile
  cmd/detect.go
  internal/configuration/validation.go
  internal/controller/controller.go
  internal/controller/controller_test.go
  internal/fans/cmd.go
  internal/fans/common.go
  internal/fans/file.go
  internal/fans/hwmon.go
  internal/fans/nvidia.go
  internal/fans/nvidia_stub.go
  internal/nvidia/nvidia.go
  internal/nvidia/nvidia_common.go
  internal/nvidia/nvidia_stub.go
  internal/nvidia_base/nvidia_base.go
  internal/nvidia_base/nvidia_base_stub.go
  internal/sensors/cmd.go
  internal/sensors/common.go
  internal/sensors/file.go
  internal/sensors/hwmon.go
  internal/sensors/nvidia.go
  internal/sensors/nvidia_stub.go
Labels: enhancement
